export {default as Homepage} from './homepage/Homepage'
export {default as LocationPage} from './locationPage/locationPage'
export {default as SchedulePage} from './schedulePage/schedulePage'
export {default as FormPage} from './formPage'
export {default as BackendTemplatePage} from './backendTemplatePage'